import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(
    `
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE TABLE product (
      id varchar(255) not null primary key DEFAULT uuid_generate_v4(),
      _id int generated by default as identity,
      name varchar(250) not null, 
      price float int not null,
      description varchar(500),
      sold int not null default 0,
      created_at timestamp without time zone not null default now(),
      updated_at timestamp without time zone not null default now(),
      deleted_at timestamp without time zone
    );`,
  );
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE product;`);
}
