import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE order_details (
      id varchar(255) not null primary key default uuid_generate_v4(),
      _id int generated by default as identity,
      created_at timestamp without time zone not null default now(),
      updated_at timestamp without time zone not null default now(),
      total_price float not null,
      status varchar(255) not null
      member_id varchar(255) REFERENCES users(id),
      address_id varchar(255) REFERENCES address(id),
      fee_id varchar(255) REFERENCES shipping_fee(id),
      shipping_method_id varchar(255) REFERENCES shipping_method(id)
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE "order_details";`);
}
