import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE discount (
      id varchar(255) not null primary key DEFAULT uuid_generate_v4(),
      _id int generated by default as identity,
      name varchar(250) not null,
      description varchar(500),
      percentage int not null CHECK(percentage >= 0 and percentage <= 100),
      active boolean not null default false,
      created_at timestamp without time zone not null default now(),
      updated_at timestamp without time zone not null default now(),
      deleted_at timestamp without time zone
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE discount;`);
}
