import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE shipping_fee (
      id varchar(255) not null primary key DEFAULT uuid_generate_v4(),
      _id int generated by default as identity,
      created_at timestamp without time zone not null default now(),
      updated_at timestamp without time zone not null default now(),
      name varchar(255) not null unique,
      fee float not null
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE "shipping_fee";`);
}
