import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE order_item (
      id varchar(255) not null primary key default uuid_generate_v4(),
      _id int generated by default as identity,
      created_at timestamp without time zone not null default now(),
      updated_at timestamp without time zone not null default now(),
      order_id varchar(255) REFERENCES order_details(id) ON DELETE CASCADE,
      price int not null,
      product_id varchar(255) not null,
      amount int not null
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE orders_item;`);
}
