version: '3.9'

services:
  product-catalog-dev:
    container_name: product-catalog-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3002:3002

  postgres:
    container_name: product-catalog-database
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
      #- ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 8002:5432

  adminer:
    container_name: product-catalog-adminer
    image: adminer
    restart: always
    ports:
      - '8902:8080'
