version: '3.9'

services:
  product-catalog:
    container_name: product-catalog-test
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    command: sh -c 'npm run schema:drop && npm run migration:up && npm run test -- $INTEGRATION_TEST'
    ports:
      - 3002:3002

  postgres:
    container_name: product-catalog-database-test
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db_test:/var/lib/postgresql/data
    ports:
      - 8002:5432
