version: '3.9'

services:
  product-catalog:
    container_name: product-catalog
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3002:3000

  postgres:
    container_name: product-catalog-database
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data:U
    ports:
      - 8002:5432

  adminer:
    container_name: product-catalog-adminer
    image: adminer
    restart: always
    ports:
      - '8902:8080'
