version: '3.9'

services:
  product-catalog:
    container_name: product-catalog-test
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    command: sh -c 'npm run schema:drop && npm run migration:up && npm run test:e2e'
    ports:
      - 3001:3000

  postgres:
    container_name: product-catalog-database-test
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db_test:/var/lib/postgresql/data
    ports:
      - 8001:5432

  adminer:
    container_name: product-catalog-adminer-test
    image: adminer
    restart: always
    ports:
      - '8901:8080'
