const ApiBaseUrl = '/api';

export const ApiApplication = {
  AUTH: {
    CONTROLLER: ApiBaseUrl + '/auth',
    LOGIN: 'log-in',
    LOGIN_DASHBOARD: 'log-in-dashboard',
    LOGOUT: 'log-out',
    GET_PROFILE: 'profile',
    IS_LOGGED_IN: 'is-logged-in',
  },
  USER: {
    CONTROLLER: ApiBaseUrl + '/user',
    CREATE_MEMBER: 'member',
    CREATE_ADMIN: 'admin',
    CREATE_STAFF: 'staff',
    CREATE_SHIPPER: 'shipper',
    GET_ALL_USER: '',
    GET_ALL_SHIPPER: 'get-all-shipper',
    GET_ALL_STAFF: 'get-all-staff',
    GET_ONE: ':id',
    UPDATE: ':id',
    UPDATE_PROFILE: 'update-profile',
    COUNT_DAILY_MEMBER: 'count-daily-member',
    COUNT_MONTHLY_MEMBER: 'count-monthly-member',
    COUNT_WEEKLY_MEMBER: 'count-weekly-member',
  },
  ADDRESS: {
    CONTROLLER: ApiBaseUrl + '/address',
    CREATE: '',
    UPDATE: ':id',
    GET_ALL: '',
    DELETE: ':id',
  },
  SHIPPING: {
    CONTROLLER: ApiBaseUrl + '/shipping',
    CREATE: '',
    UPDATE: ':id',
    UPDATE_STATUS: 'update-status/:id',
    DELETE_BY_ORDER: ':orderId',
    GET_ALL: '',
    GET_ONE: ':id',
    GET_BY_ORDER_ID: 'get-by-order',
    GET_BY_SHIPPER_ID: 'get-by-shipper',
  },
  SHIPPING_FEE: {
    CONTROLLER: ApiBaseUrl + '/shipping-fee',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_ALL: '',
    GET_ONE: ':id',
  },
  PRODUCT: {
    CONTROLLER: ApiBaseUrl + '/product',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    DELETE_MANY: 'delete-many',
    GET_ALL: '',
    GET_ALL_BY_CATEGORY: 'get-all-by-category',
    GET_ALL_WITH_IMAGES: 'get-all-with-images',
    GET_ONE: ':id',
    GET_DAILY_SOLD: 'get-daily-sold',
    GET_WEEKLY_SOLD: 'get-weekly-sold',
    GET_MONTHLY_SOLD: 'get-monthly-sold',
  },
  CATEGORY: {
    CONTROLLER: ApiBaseUrl + '/category',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_ALL: '',
    GET_ALL_WITH_PRODUCT_COUNT: 'get-all-with-product-count',
    GET_ONE: ':id',
  },
  PRODUCT_CATEGORY: {
    CONTROLLER: ApiBaseUrl + '/product-category',
    GET_PRODUCTS_BY_CATEGORY: 'get-products-by-category',
  },
  DISCOUNT: {
    CONTROLLER: ApiBaseUrl + '/discount',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    DELETE_MANY: 'delete-many',
    GET_ALL: '',
    GET_ALL_WITH_PRODUCT_COUNT: 'get-all-with-product-count',
    GET_ONE: ':id',
  },
  CART: {
    CONTROLLER: ApiBaseUrl + '/cart',
    CREATE: '',
    UPDATE: '',
    GET: '',
    GET_ITEMS: 'items',
    GET_TOTAL_PRICE: 'total-price',
    CLEAR: 'clear',
  },
  CART_ITEM: {
    CONTROLLER: ApiBaseUrl + '/cart-item',
    CREATE: '',
    UPDATE: ':id',
    UPSERT: 'upsert',
    DELETE: ':id',
    GET_BY_CART_ID: ':cartId',
    GET_BY_USER_ID: 'get-by-user-id',
  },
  UPLOAD: {
    CONTROLLER: ApiBaseUrl + '/upload',
    UPLOAD: '',
    DESTROY: 'destroy',
  },
  PRODUCT_IMAGE: {
    CONTROLLER: ApiBaseUrl + '/product-image',
    ADD: '',
    GET_PRODUCT_IMAGES: ':productId',
    REMOVE: 'remove',
  },
  ORDER: {
    CONTROLLER: ApiBaseUrl + '/order',
    CREATE: '',
    GET_BY_MEMBER: 'get-by-member',
    GET_ALL: '',
    UPDATE: ':id',
    GET_ONE: ':orderId',
    COUNT_DAILY: 'count-daily',
    COUNT_WEEKLY: 'count-weekly',
    COUNT_MONTHLY: 'count-monthly',
  },
  ORDER_ITEM: {
    CONTROLLER: ApiBaseUrl + '/order-item',
    GET_BY_ORDER_ID: 'get-by-order-id',
  },
  INCOME: {
    CONTROLLER: ApiBaseUrl + '/income',
    GET_DAILY: 'get-daily',
    GET_WEEKLY: 'get-weekly',
    GET_MONTHLY: 'get-monthly',
    GET_YEARLY: 'get-yearly',
  },
  SHIPPING_STATUS: {
    CONTROLLER: ApiBaseUrl + '/shipping-status',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_BY_SHIPPING_ID: 'get-by-shipping-id',
    GET_BY_ORDER_ID: 'get-by-order-id',
    GET_ONE: ':id',
  },
};
