export const DATABASE_TABLE = {
  SHIPPING: {
    NAME: 'shipping',
    SCHEMA: {
      ID: 'id',
      DUE_DATE: 'due_date',
      ORDER_ID: 'order_id',
      SHIPPER_ID: 'shipper_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  SHIPPING_FEE: {
    NAME: 'shipping_fee',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      FEE: 'fee',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  SHIPPING_STATUS: {
    NAME: 'shipping_status',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  SHIPPING_METHOD: {
    NAME: 'shipping_method',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  USERS: {
    NAME: 'users',
    SCHEMA: {
      ID: 'id',
      USERNAME: 'username',
      HASHED: 'hashed',
      PASSWORD: 'password',
      FULL_NAME: 'full_name',
      ROLE: 'role',
      PHONE: 'phone',
      EMAIL: 'email',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  ADDRESS: {
    NAME: 'address',
    SCHEMA: {
      ID: 'id',
      LOCATION: 'location',
      USER_ID: 'user_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  PRODUCT: {
    NAME: 'product',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      PRICE: 'price',
      DESCRIPTION: 'description',
      IMAGE_URL: 'image_url',
      DISCOUNT_ID: 'discount_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  DISCOUNT: {
    NAME: 'discount',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      DESCRIPTION: 'description',
      PERCENTAGE: 'percentage',
      ACTIVE: 'active',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  CATEGORY: {
    NAME: 'category',
    SCHEMA: {
      ID: 'id',
      NAME: 'name',
      DESCRIPTION: 'description',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  PRODUCT_IMAGE: {
    NAME: 'product_image',
    SCHEMA: {
      ID: 'id',
      PRODUCT_ID: 'product_id',
      URL: 'url',
      CREATED_AT: 'created_at',
    },
  },
  PRODUCT_CATEGORY: {
    NAME: 'product_category',
    SCHEMA: {
      ID: 'id',
      PRODUCT_ID: 'product_id',
      CATEGORY_ID: 'category_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  CART: {
    NAME: 'cart',
    SCHEMA: {
      ID: 'id',
      TOTAL_PRICE: 'total_price',
      MEMBER_ID: 'member_id',
      SHIPPING_FEE_ID: 'shipping_fee_id',
      ADDRESS_ID: 'address_id',
      SHIPPING_METHOD_ID: 'shipping_method_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  CART_ITEM: {
    NAME: 'cart_item',
    SCHEMA: {
      ID: 'id',
      CART_ID: 'cart_id',
      PRODUCT_ID: 'product_id',
      AMOUNT: 'amount',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  ORDER_DETAILS: {
    NAME: 'order_details',
    SCHEMA: {
      ID: 'id',
      MEMBER_ID: 'member_id',
      TOTAL_PRICE: 'total_price',
      STATUS: 'status',
      ADDRESS_ID: 'address_id',
      SHIPPING_FEE_ID: 'shipping_fee_id',
      SHIPPING_METHOD_ID: 'shipping_method_id',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
  ORDER_ITEM: {
    NAME: 'order_item',
    SCHEMA: {
      ID: 'id',
      ORDER_ID: 'order_id',
      PRODUCT_ID: 'product_id',
      AMOUNT: 'amount',
      PRICE: 'price',
      CREATED_AT: 'created_at',
      UPDATED_AT: 'updated_at',
    },
  },
};
