export const GlobalEvents = {
  USER: {
    MEMBER_CREATED: 'USER.MEMBER_CREATED',
  },
  ORDER: {
    ORDER_CREATED: 'ORDER.ORDER_CREATED',
  },
  SHIPPING: {
    CREATED: 'SHIPPING.SHIPPING_CREATED',
    STATUS_UPDATED: 'SHIPPING.STATUS_UPDATED',
  },
};
