export const GlobalEvents = {
  USER: {
    CREATED: 'USER.CREATED',
  },
  ORDER: {
    CREATED: 'ORDER.CREATED',
    UPDATED: 'ORDER.UPDATED',
  },
  SHIPPING: {
    CREATED: 'SHIPPING.CREATED',
    DELETED: 'SHIPPING.DELETED',
    STATUS_UPDATED: 'SHIPPING.STATUS_UPDATED',
  },
  ADDRESS: {
    DELETED: 'ADDRESS.DELETED',
  },
  SHIPPING_FEE: {
    DELETED: 'SHIPPING_FEE.DELETED',
  },
};
