/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddSubCategoriesHttpRequest
 */
export interface AddSubCategoriesHttpRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof AddSubCategoriesHttpRequest
     */
    subCategoryIds: Array<string>;
}

/**
 * Check if a given object implements the AddSubCategoriesHttpRequest interface.
 */
export function instanceOfAddSubCategoriesHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subCategoryIds" in value;

    return isInstance;
}

export function AddSubCategoriesHttpRequestFromJSON(json: any): AddSubCategoriesHttpRequest {
    return AddSubCategoriesHttpRequestFromJSONTyped(json, false);
}

export function AddSubCategoriesHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSubCategoriesHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subCategoryIds': json['subCategoryIds'],
    };
}

export function AddSubCategoriesHttpRequestToJSON(value?: AddSubCategoriesHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subCategoryIds': value.subCategoryIds,
    };
}

