/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApproveProductHttpRequest
 */
export interface ApproveProductHttpRequest {
    /**
     * Reviewer Id
     * @type {string}
     * @memberof ApproveProductHttpRequest
     */
    reviewerId: string;
}

/**
 * Check if a given object implements the ApproveProductHttpRequest interface.
 */
export function instanceOfApproveProductHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reviewerId" in value;

    return isInstance;
}

export function ApproveProductHttpRequestFromJSON(json: any): ApproveProductHttpRequest {
    return ApproveProductHttpRequestFromJSONTyped(json, false);
}

export function ApproveProductHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveProductHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reviewerId': json['reviewerId'],
    };
}

export function ApproveProductHttpRequestToJSON(value?: ApproveProductHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reviewerId': value.reviewerId,
    };
}

