/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReviewerHttpRequest
 */
export interface CreateReviewerHttpRequest {
    /**
     * The name of the reviewer
     * @type {string}
     * @memberof CreateReviewerHttpRequest
     */
    name: string;
    /**
     * The email of the reviewer
     * @type {string}
     * @memberof CreateReviewerHttpRequest
     */
    email: string;
    /**
     * The role of the reviewer
     * @type {string}
     * @memberof CreateReviewerHttpRequest
     */
    role: CreateReviewerHttpRequestRoleEnum;
}


/**
 * @export
 */
export const CreateReviewerHttpRequestRoleEnum = {
    Regular: 'regular',
    Admin: 'admin'
} as const;
export type CreateReviewerHttpRequestRoleEnum = typeof CreateReviewerHttpRequestRoleEnum[keyof typeof CreateReviewerHttpRequestRoleEnum];


/**
 * Check if a given object implements the CreateReviewerHttpRequest interface.
 */
export function instanceOfCreateReviewerHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function CreateReviewerHttpRequestFromJSON(json: any): CreateReviewerHttpRequest {
    return CreateReviewerHttpRequestFromJSONTyped(json, false);
}

export function CreateReviewerHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReviewerHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'role': json['role'],
    };
}

export function CreateReviewerHttpRequestToJSON(value?: CreateReviewerHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'role': value.role,
    };
}

