/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateProductHttpRequestPrice } from './CreateProductHttpRequestPrice';
import {
    CreateProductHttpRequestPriceFromJSON,
    CreateProductHttpRequestPriceFromJSONTyped,
    CreateProductHttpRequestPriceToJSON,
} from './CreateProductHttpRequestPrice';

/**
 * 
 * @export
 * @interface CreateProductHttpRequest
 */
export interface CreateProductHttpRequest {
    /**
     * The name of the product
     * @type {string}
     * @memberof CreateProductHttpRequest
     */
    name: string;
    /**
     * 
     * @type {CreateProductHttpRequestPrice}
     * @memberof CreateProductHttpRequest
     */
    price: CreateProductHttpRequestPrice;
    /**
     * The description of the product
     * @type {string}
     * @memberof CreateProductHttpRequest
     */
    description: string;
    /**
     * The image of the product
     * @type {string}
     * @memberof CreateProductHttpRequest
     */
    image: string;
}

/**
 * Check if a given object implements the CreateProductHttpRequest interface.
 */
export function instanceOfCreateProductHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function CreateProductHttpRequestFromJSON(json: any): CreateProductHttpRequest {
    return CreateProductHttpRequestFromJSONTyped(json, false);
}

export function CreateProductHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': CreateProductHttpRequestPriceFromJSON(json['price']),
        'description': json['description'],
        'image': json['image'],
    };
}

export function CreateProductHttpRequestToJSON(value?: CreateProductHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': CreateProductHttpRequestPriceToJSON(value.price),
        'description': value.description,
        'image': value.image,
    };
}

