/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The price of the product
 * @export
 * @interface CreateProductHttpRequestPrice
 */
export interface CreateProductHttpRequestPrice {
    /**
     * The amount of the price
     * @type {number}
     * @memberof CreateProductHttpRequestPrice
     */
    amount?: number;
    /**
     * The currency of the price
     * @type {string}
     * @memberof CreateProductHttpRequestPrice
     */
    currency?: string;
}

/**
 * Check if a given object implements the CreateProductHttpRequestPrice interface.
 */
export function instanceOfCreateProductHttpRequestPrice(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateProductHttpRequestPriceFromJSON(json: any): CreateProductHttpRequestPrice {
    return CreateProductHttpRequestPriceFromJSONTyped(json, false);
}

export function CreateProductHttpRequestPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductHttpRequestPrice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
    };
}

export function CreateProductHttpRequestPriceToJSON(value?: CreateProductHttpRequestPrice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
    };
}

