/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RejectProductHttpRequest
 */
export interface RejectProductHttpRequest {
    /**
     * ID of the reviewer
     * @type {string}
     * @memberof RejectProductHttpRequest
     */
    reviewerId: string;
    /**
     * Reason for rejection
     * @type {string}
     * @memberof RejectProductHttpRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the RejectProductHttpRequest interface.
 */
export function instanceOfRejectProductHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reviewerId" in value;
    isInstance = isInstance && "reason" in value;

    return isInstance;
}

export function RejectProductHttpRequestFromJSON(json: any): RejectProductHttpRequest {
    return RejectProductHttpRequestFromJSONTyped(json, false);
}

export function RejectProductHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectProductHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reviewerId': json['reviewerId'],
        'reason': json['reason'],
    };
}

export function RejectProductHttpRequestToJSON(value?: RejectProductHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reviewerId': value.reviewerId,
        'reason': value.reason,
    };
}

