/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitForApprovalHttpRequest
 */
export interface SubmitForApprovalHttpRequest {
    /**
     * ID of the reviewer
     * @type {string}
     * @memberof SubmitForApprovalHttpRequest
     */
    reviewerId: string;
}

/**
 * Check if a given object implements the SubmitForApprovalHttpRequest interface.
 */
export function instanceOfSubmitForApprovalHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reviewerId" in value;

    return isInstance;
}

export function SubmitForApprovalHttpRequestFromJSON(json: any): SubmitForApprovalHttpRequest {
    return SubmitForApprovalHttpRequestFromJSONTyped(json, false);
}

export function SubmitForApprovalHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitForApprovalHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reviewerId': json['reviewerId'],
    };
}

export function SubmitForApprovalHttpRequestToJSON(value?: SubmitForApprovalHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reviewerId': value.reviewerId,
    };
}

