/* tslint:disable */
/* eslint-disable */
/**
 * Product Catalog API
 * Manage your products
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductHttpRequest
 */
export interface UpdateProductHttpRequest {
    /**
     * The name of the product
     * @type {string}
     * @memberof UpdateProductHttpRequest
     */
    name: string;
    /**
     * The price of the product
     * @type {object}
     * @memberof UpdateProductHttpRequest
     */
    price: object;
    /**
     * The description of the product
     * @type {string}
     * @memberof UpdateProductHttpRequest
     */
    description: string;
    /**
     * The image of the product
     * @type {string}
     * @memberof UpdateProductHttpRequest
     */
    image: string;
}

/**
 * Check if a given object implements the UpdateProductHttpRequest interface.
 */
export function instanceOfUpdateProductHttpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function UpdateProductHttpRequestFromJSON(json: any): UpdateProductHttpRequest {
    return UpdateProductHttpRequestFromJSONTyped(json, false);
}

export function UpdateProductHttpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductHttpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'description': json['description'],
        'image': json['image'],
    };
}

export function UpdateProductHttpRequestToJSON(value?: UpdateProductHttpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
        'description': value.description,
        'image': value.image,
    };
}

